### PR TITLE
Add BinlogDumpPacket and RegisterSlavePacket

### PR DESCRIPTION
**Pull request by utay**
Adding those packet definitions as per the docs:
- https://dev.mysql.com/doc/internals/en/com-binlog-dump.html for `BinlogDumpPacket`
- https://dev.mysql.com/doc/internals/en/com-register-slave.html for `RegisterSlavePacket`

I've tested it in a personal crate and confirm I'm able to get a binlog stream from the server with them!

### CODE REVIEW

**Comment by blackbeam** [comment]
Hi. Please look into the [`binlog`][1] branch. Namely [here][2] and [here][3].

Looks like I should find time and finally merge this into the master..

[1]: https://github.com/blackbeam/rust_mysql_common/tree/binlog
[2]: https://github.com/blackbeam/rust_mysql_common/blob/binlog/src/packets.rs#L1517
[3]: https://github.com/blackbeam/rust_mysql_common/blob/binlog/src/packets.rs#L1749

**Comment by blackbeam** [comment]
* [here][1] is the corresponding (outdated) `mysql_async` branch;
* related issue – blackbeam/mysql_async#99

[1]: https://github.com/blackbeam/mysql_async/tree/binlog-stream

**Comment by utay** [comment]
@blackbeam Oh, missed it, that's nice! Any ETA on when the `binlog` branch will get merged into master? In the meantime I can target this branch from my Cargo.toml. Closing this PR as your binlog implem is way more advanced

**Comment by utay** [comment]
Also, any plan to implement binlog streams in https://github.com/blackbeam/rust-mysql-simple?

**Pull request closed without merging**
